module.exports = {
  apps: [
    {
      name: 'whale-tracker',
      cwd: __dirname,
      script: 'npm',
      args: 'run whale:tracker',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      time: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'whale-scout',
      cwd: __dirname,
      script: 'npm',
      args: 'run whale:scout',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      time: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'position-manager',
      cwd: __dirname,
      script: 'npm',
      args: 'run position:manager',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      time: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'dashboard',
      cwd: __dirname,
      script: 'npm',
      args: 'run dashboard',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      time: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'profit-report',
      cwd: __dirname,
      script: 'npm',
      args: 'run profit:report',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      time: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: 'production',
      },
    },
  ],
};